apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-amqstreams-consumer-scaledobject
spec:
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod: 5
  pollingInterval: 10
  fallback:
    failureThreshold: 3
    replicas: 2
  scaleTargetRef:
    name: kafka-amqstreams-consumer
  triggers:
  - type: kafka
    metadata:
      topic: my-topic
      bootstrapServers: my-cluster-kafka-bootstrap.openshift-operators.svc:9092
      consumerGroup: my-group
      lagThreshold: '1'
      offsetResetPolicy: 'latest'